SPARSERT_DIR = '../SparseRT/'
SPARSERT_MATERIALS_DIR = '{}materials/'.format(SPARSERT_DIR)
SPARSERT_MATERIALS_DATA_DIR = '{}data/'.format(SPARSERT_MATERIALS_DIR)
SPARSERT_MATERIALS_DIST_DIR = '{}dist/'.format(SPARSERT_MATERIALS_DIR)
SPARSERT_MATERIALS_TEMP_DIR = '{}temp/'.format(SPARSERT_MATERIALS_DIR)
